### PR TITLE
CMake: CONFIG_PREFIX handles the deployment path of config files.

### PR DESCRIPTION
**Pull request by JensLorenz**
@MathieuDuponchelle, @tisogai, @GeniviAMmaintainer: Please test and give feedback. Consider to merge before #3.

### CODE REVIEW

**Comment by MathieuDuponchelle** [comment]
lgtm

**Comment by JensLorenz** [comment]
@GeniviAMmaintainer: Please merge the PR.

**Comment by MathieuDuponchelle** [comment]
Looks good to me

**Comment by MathieuDuponchelle** [comment]
@JensLorenz , actually two remarks:

1. You should name the option GENERIC_CONTROLLER_CONFIG_PREFIX

2. the commit message isn't very good, what about:

```
CMake: expose a GENERIC_CONTROLLER_CONFIG_PREFIX option.

This gives control to the user over where the generic controller's configuration
files will be installed and where the generic controller will look them up.

Defaults to CMAKE_INSTALL_PREFIX.
```

**Comment by JensLorenz** [comment]
@MathieuDuponchelle I fully agree on the second that commit messages should be more verbose. I don't agree to the first. CONFIG_PREFIX should be used because it is meant to be generic for all plugins deploying configuration files to the system but this is a taste.

**Comment by MathieuDuponchelle** [comment]
@JensLorenz , OK. Also, I am not a CMake expert at all, any idea how that sort of configure option should be documented?

**Comment by JensLorenz** [comment]
@MathieuDuponchelle You are right, the documentation should be extended. We will provide an additional patch for it later after #3 has been merged.

**Comment by MathieuDuponchelle** [comment]
@JensLorenz , can you not rebase your work, fix up the commits together, give the commit a better message and document the switch ?

**Pull request closed without merging**
